# DS2002 · Pandas Challenge

**Lab — 2026-09-18 · Fall 2026**  

---

## Lab 04 — Pandas Challenge

Four hundred generated orders. Each question builds toward a demand report you could hand a vendor.

The data is seeded, so everyone's numbers should match. That is deliberate: if your total revenue differs from your neighbor's, one of you has a bug, and the assertions at the end will tell you which.

Every answer needs the number **and** a sentence saying what it means. A cell that prints `4218.5` with no interpretation is half an answer.

In [2]:
import pandas as pd, numpy as np
rng = np.random.default_rng(4)
n = 400
df = pd.DataFrame({
    'vendor_id': rng.choice(['V-01','V-05','V-10','V-18'], n),
    'category': rng.choice(['Food','Merch','RainGear','Drink'], n, p=[.5,.2,.1,.2]),
    'qty': rng.integers(1, 4, n),
    'price': rng.choice([4.5, 6.0, 7.5, 12.0, 24.0], n),
})
df.head()

  vendor_id  category  qty  price
0      V-10     Drink    2   24.0
1      V-18  RainGear    1   12.0
2      V-18     Drink    3    4.5
3      V-10      Food    2   12.0
4      V-18     Drink    3    7.5

### Q1 — Add `revenue`, then report total revenue and total units.

*Expected: 400 rows, and revenue should land between $8,000 and $9,000.*

In [3]:
# TODO
df['revenue'] = df['qty'] * df['price']
total_units = int(df['qty'].sum())
total_revenue = int(df['revenue'].sum())
'''
The total revenue and total unit tells us that on average each unit sold for $10.88
'''
print(f"Total Revenue: {total_revenue}, Total Units: {total_units}")

Total Revenue: 8520, Total Units: 783

### Q2 — Revenue by category, highest to lowest.

Include the share of total as a percentage in the same table.

In [4]:
# TODO
df['percentage share'] = df['revenue']/total_revenue * 100
'''
About 50% of all revenue comes from food while Merch, drink, and rain gear make up the other 50% with rain gear making the lowest percentage return
'''
df.groupby('category').agg(revenue = ('revenue', 'sum'), percentage = ('percentage share', 'sum')).round(2).sort_values(by='revenue', ascending=False)

          revenue  percentage
category
Food       4293.0       50.39
Merch      1771.5       20.79
Drink      1554.0       18.24
RainGear    901.5       10.58

### Q3 — Which vendor has the highest *average* order revenue?

Report the average alongside the order count for each vendor. A high average on twelve orders is a different claim from a high average on two hundred.

In [5]:
# TODO
'''
Smaller count skews the total value as both V-18 and V-10 total revenue is more than V-01
'''
df.groupby('vendor_id').agg(order_average = ('revenue', 'mean'), order_count = ('vendor_id', 'count')).round(2).sort_values(by='order_average', ascending=False)

           order_average  order_count
vendor_id
V-01               22.60           94
V-18               21.75          108
V-05               20.58           93
V-10               20.31          105

### Q4 — What share of revenue comes from Merch?

Print it as a percentage rounded to one decimal.

In [6]:
# TODO
total_merch = df[df['category'] == 'Merch'].sum()
merch_percenatage = float(total_merch['revenue']/total_revenue)*100
'''
Merch accounts for 1/4 of all the total revenue made 
'''
print(f"merch percentage to total revenue: {round(merch_percenatage, 1)}")

merch percentage to total revenue: 20.8

### Q5 — Join in the vendor names.

The frame only has `vendor_id`. Merge the lookup below so your report is readable.

**Requirements:** left join, `validate='many_to_one'`, and prove the row count and revenue total did not change. One vendor id in the orders is not in this lookup — find it, and decide what to do about it.

In [11]:
vendor_names = pd.DataFrame({
    'vendor_id': ['V-01', 'V-05', 'V-10'],
    'vendor_name': ['Hoos Burgers', 'Rotunda Tacos', 'Cav Merch North'],
})
# TODO: merge, validate, and report the unmatched vendor
merged_data = df.merge(vendor_names, on='vendor_id', how='left', validate='many_to_one')
merged_data.head()

  vendor_id  category  qty  price  revenue  percentage share      vendor_name
0      V-10     Drink    2   24.0     48.0          0.563380  Cav Merch North
1      V-18  RainGear    1   12.0     12.0          0.140845              NaN
2      V-18     Drink    3    4.5     13.5          0.158451              NaN
3      V-10      Food    2   12.0     24.0          0.281690  Cav Merch North
4      V-18     Drink    3    7.5     22.5          0.264085              NaN

**The unmatched vendor, and what I did about it:** The unmatched vendor is V-18 and what I did was just to keep the data inside but the vendor_name is NaN as the revenue was about 30% of the total revenue

### Q6 — A pivot table: vendors down the side, categories across the top, revenue in the cells.

Add row and column totals so it reads as a report rather than a grid of numbers.

In [ ]:
# TODO

### Q7 — Validate your work

**TODO:** uncomment and make these pass. Assign your results to the named variables as you go.

In [ ]:
# assert len(df) == 400
# assert 8000 < df['revenue'].sum() < 9000, df['revenue'].sum()
# assert abs(by_category['revenue'].sum() - df['revenue'].sum()) < 0.01
# assert len(joined) == len(df), 'the vendor merge changed the row count'
print('checks passed.')

checks passed.

### Write-up

**a)** What would you tell these vendors to do differently next game? One paragraph, with at least two numbers from your report in it.

**b)** Which of your seven answers is the least trustworthy, and why? Point at a specific weakness — a small group size, an unmatched vendor, a category that is really two things.

_your answer here_